version: '2'
services:
  web:
    image: nginx:1.11.1
    ports:
    - "8080:80"
    volumes:
    -  ./nginx.conf:/etc/nginx/nginx.conf:ro
    -  ./nginx-contacts-ui.conf:/etc/nginx/conf.d/default.conf:ro
    - ./dist:/usr/share/nginx/html:ro
    environment:
    - FUM_BASEURL
    - AVATAR_BASEURL
    links:
    - api
  api:
    image: nginx:1.11.1
    ports:
    - "8081:80"
    volumes:
    - ./mock-contacts-api:/usr/share/nginx/html:ro
